server:
  port: 31001
spring:
  application:
    name: ch-service-manage-cms
  data:
    mongodb:
      database: ch_cms
      uri: mongodb://root:123456@localhost:27017
  freemarker:
    cache: false #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0 #检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便进行模板测试
      classic_compatible: true #处理空值
      datetime_format: yyyy-MM-dd HH:mm
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /
eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: http://localhost:50101/eureka