server:
  port: 31000
spring:
  application:
    name: ch-service-manage-cms-client
  data:
    mongodb:
      uri: mongodb://root:123456@localhost:27017
      database: ch_cms
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /

chuhang:
  mq:
    #cms客户端监控的队列名称（不同的客户端监控的队列不能重复）
    #queue: queue_cms_postpage_01
    #routingKey: 5a751fab6abb5044e0d19ea1 #此routingKey为门户站点ID
    queue: queue_cms_postpage_02
    routingKey: 5b30b052f58b4411fc6cb1cf #此routingKey为课程详情站点ID